### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by backlin** [jeetsukumaran/Syrupy#2]
Not sure what flavor of markdown you are using in the README file, but on GitHub the links to the `ps` Wikipedia page contain some training characters that break the links. At the moment they point to "http://en.wikipedia.org/wiki/Ps_(Unix)>`_" instead of "http://en.wikipedia.org/wiki/Ps_(Unix)".

**Comment by jeetsukumaran** [comment]
Thanks. I actually used ReStructredText, which apparently does not get parsed correctly by GitHub if the filename extension is ".txt" (which is what is recommended). Changed the extension to accommodate.
